export const GET_ME_REQUEST = '@user/GET_ME_REQUEST';
export const GET_ME_SUCCESS = '@user/GET_ME_SUCCESS';
export const GET_ME_FAILED = '@user/GET_ME_FAILED';

export const UPDATE_PROFILE_IMAGE_REQUEST = '@user/UPDATE_PROFILE_IMAGE_REQUEST';
export const UPDATE_PROFILE_IMAGE_SUCCESS = '@user/UPDATE_PROFILE_IMAGE_SUCCESS';
export const UPDATE_PROFILE_IMAGE_FAILED = '@user/UPDATE_PROFILE_IMAGE_FAILED';

export const UPDATE_COVER_IMAGE_REQUEST = '@user/UPDATE_COVER_IMAGE_REQUEST';
export const UPDATE_COVER_IMAGE_SUCCESS = '@user/UPDATE_COVER_IMAGE_SUCCESS';
export const UPDATE_COVER_IMAGE_FAILED = '@user/UPDATE_COVER_IMAGE_FAILED';

export const UPDATE_NAME_REQUEST = '@user/UPDATE_NAME_REQUEST';
export const UPDATE_NAME_SUCCESS = '@user/UPDATE_NAME_SUCCESS';
export const UPDATE_NAME_FAILED = '@user/UPDATE_NAME_FAILED';

export const ADD_FOLLOWING_REQUEST = '@user/ADD_FOLLOWING_REQUEST';
export const ADD_FOLLOWING_SUCCESS = '@user/ADD_FOLLOWING_SUCCESS';
export const ADD_FOLLOWING_FAILED = '@user/ADD_FOLLOWING_FAILED';
