export const UPDATE_PROFILE_IMAGE_REQUEST = '@user/UPDATE_PROFILE_IMAGE_REQUEST';
export const UPDATE_PROFILE_IMAGE_SUCCESS = '@user/UPDATE_PROFILE_IMAGE_SUCCESS';
export const UPDATE_PROFILE_IMAGE_FAILED = '@user/UPDATE_PROFILE_IMAGE_FAILED';

export const UPDATE_COVER_IMAGE_REQUEST = '@user/UPDATE_COVER_IMAGE_REQUEST';
export const UPDATE_COVER_IMAGE_SUCCESS = '@user/UPDATE_COVER_IMAGE_SUCCESS';
export const UPDATE_COVER_IMAGE_FAILED = '@user/UPDATE_COVER_IMAGE_FAILED';
