export const ADD_TWEET_REQUEST = '@tweet/ADD_TWEET_REQUEST';
export const ADD_TWEET_SUCCESS = '@tweet/ADD_TWEET_SUCCESS';
export const ADD_TWEET_FAILED = '@tweet/ADD_TWEET_FAILED';

export const FETCH_TWEET_REQUEST = '@tweet/FETCH_TWEET_REQUEST';
export const FETCH_TWEET_SUCCESS = '@tweet/FETCH_TWEET_SUCCESS';
export const FETCH_TWEET_FAILED = '@tweet/FETCH_TWEET_FAILED';

export const UPDATE_TWEET_REQUEST = '@tweet/UPDATE_TWEET_REQUEST';
export const UPDATE_TWEET_SUCCESS = '@tweet/UPDATE_TWEET_SUCCESS';
export const UPDATE_TWEET_FAILED = '@tweet/UPDATE_TWEET_FAILED';

export const DELETE_TWEET_REQUEST = '@tweet/DELETE_TWEET_REQUEST';
export const DELETE_TWEET_SUCCESS = '@tweet/DELETE_TWEET_SUCCESS';
export const DELETE_TWEET_FAILED = '@tweet/DELETE_TWEET_FAILED';
