export const ADD_CATEGORY_REQUEST = '@category/ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = '@category/ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = '@category/ADD_CATEGORY_FAILED';

export const FETCH_CATEGORY_REQUEST = '@category/FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = '@category/FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = '@category/FETCH_CATEGORY_FAILED';

export const UPDATE_CATEGORY_REQUEST = '@category/UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = '@category/UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = '@category/UPDATE_CATEGORY_FAILED';

export const DELETE_CATEGORY_REQUEST = '@category/DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = '@category/DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = '@category/DELETE_CATEGORY_FAILED';
