export const ADD_AUTHOR_REQUEST = '@author/ADD_AUTHOR_REQUEST';
export const ADD_AUTHOR_SUCCESS = '@author/ADD_AUTHOR_SUCCESS';
export const ADD_AUTHOR_FAILED = '@author/ADD_AUTHOR_FAILED';

export const FETCH_AUTHOR_REQUEST = '@author/FETCH_AUTHOR_REQUEST';
export const FETCH_AUTHOR_SUCCESS = '@author/FETCH_AUTHOR_SUCCESS';
export const FETCH_AUTHOR_FAILED = '@author/FETCH_AUTHOR_FAILED';

export const UPDATE_AUTHOR_REQUEST = '@author/UPDATE_AUTHOR_REQUEST';
export const UPDATE_AUTHOR_SUCCESS = '@author/UPDATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_FAILED = '@author/UPDATE_AUTHOR_FAILED';

export const DELETE_AUTHOR_REQUEST = '@author/DELETE_AUTHOR_REQUEST';
export const DELETE_AUTHOR_SUCCESS = '@author/DELETE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_FAILED = '@author/DELETE_AUTHOR_FAILED';
