export const ADD_BOOK_REQUEST = '@book/ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = '@book/ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILED = '@book/ADD_BOOK_FAILED';

export const FETCH_BOOK_REQUEST = '@book/FETCH_BOOK_REQUEST';
export const FETCH_BOOK_SUCCESS = '@book/FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_FAILED = '@book/FETCH_BOOK_FAILED';

export const UPDATE_BOOK_REQUEST = '@book/UPDATE_BOOK_REQUEST';
export const UPDATE_BOOK_SUCCESS = '@book/UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILED = '@book/UPDATE_BOOK_FAILED';

export const DELETE_BOOK_REQUEST = '@book/DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = '@book/DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILED = '@book/DELETE_BOOK_FAILED';

export const ADD_COMMENT_SUCCESS = '@book/ADD_COMMENT_SUCCESS';
